### ISSUE TITLE
打补丁可以实现s3睡眠，但是合盖没法息屏，不知道怎么用SSDT来修复

### ISSUE THREAD

**Issue by JokerAB** [akwangl/RedmiBook-Pro-15S-hackintosh#1]

**Comment by lwh110221** [comment]
打的哪个补丁 盒盖那玩意我能搞

**Comment by lwh110221** [comment]
> > _No description provided._
> 
> 求问，打什么补丁

打我的补丁

**Comment by deanls1** [comment]
在哪里

**Comment by JokerAB** [comment]
Find      A01D9343 4E534200 A0159344 41533301         Replace      A3A3A3A3 A3A3A3A3 A3A3A3A3 A3A3A3A3就可以开启S3睡眠了
<img width="699" alt="截图" src="https://github.com/user-attachments/assets/d4ae31b8-afbe-4a7f-b7cb-0f87fe9e5bc6">

不过开了S3睡眠，电量会一直显示100%

**Comment by deanls1** [comment]
> Find A01D9343 4E534200 A0159344 41533301 Replace A3A3A3A3 A3A3A3A3 A3A3A3A3 A3A3A3A3就可以开启S3睡眠了 <img alt="截图" width="699" src="https://private-user-images.githubusercontent.com/49889696/361369150-c65eb917-87ff-435b-b28d-a286cd7f6d21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MjMyNDksIm5iZiI6MTcyNDcyMjk0OSwicGF0aCI6Ii80OTg4OTY5Ni8zNjEzNjkxNTAtYzY1ZWI5MTctODdmZi00MzViLWIyOGQtYTI4NmNkN2Y2ZDIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAxNDIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYTQwNmE5Mjk3M2U0ZGU3MzExNDIxODhjMjNlOTg3OTA2MmQ2MGFlYTk3YWE3ZmM2Y2Q2OGUyNTA2MjRmOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HZtG_U39JrYOZXQTxj4DsRvQNRKOkVaSLudt3z4b-GU"> 不过开了S3睡眠，电量会一直显示100%

会反复using AC 到darkwake，且不显示原因
<img width="527" alt="image" src="https://github.com/user-attachments/assets/2a6c077f-3bba-4039-83e9-18e672fe09e4">

**Comment by akwangl** [comment]
用越南老哥那个ACPI补丁，BIOS开启s3能深度睡眠，但是电量显示100，一直不掉电

**Comment by akwangl** [comment]
我换个白果网卡之后试试睡眠

**Comment by akwangl** [comment]
> Find A01D9343 4E534200 A0159344 41533301 Replace A3A3A3A3 A3A3A3A3 A3A3A3A3 A3A3A3A3就可以开启S3睡眠了 <img alt="截图" width="699" src="https://private-user-images.githubusercontent.com/49889696/361369150-c65eb917-87ff-435b-b28d-a286cd7f6d21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Mjc3NTMsIm5iZiI6MTcyNDcyNzQ1MywicGF0aCI6Ii80OTg4OTY5Ni8zNjEzNjkxNTAtYzY1ZWI5MTctODdmZi00MzViLWIyOGQtYTI4NmNkN2Y2ZDIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAyNTczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmNWZkMzJkZGRmMzMxOTMzZTI0NDJhNmJkZmI1ZGIzOWIyZWZjNzIxZDQyYTc2NDEzNGE5MjRhNjhlODRhODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TpZYrfcvaP58w3thOUqsjJ4VvzAUny9BpBSs52V6i-E"> 不过开了S3睡眠，电量会一直显示100%

能附带efi文件的xml信息吗

**Comment by JokerAB** [comment]
> > Find A01D9343 4E534200 A0159344 41533301 Replace A3A3A3A3 A3A3A3A3 A3A3A3A3 A3A3A3A3就可以开启S3睡眠了 <img alt="截图" width="699" src="https://private-user-images.githubusercontent.com/49889696/361369150-c65eb917-87ff-435b-b28d-a286cd7f6d21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MjMyNDksIm5iZiI6MTcyNDcyMjk0OSwicGF0aCI6Ii80OTg4OTY5Ni8zNjEzNjkxNTAtYzY1ZWI5MTctODdmZi00MzViLWIyOGQtYTI4NmNkN2Y2ZDIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAxNDIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYTQwNmE5Mjk3M2U0ZGU3MzExNDIxODhjMjNlOTg3OTA2MmQ2MGFlYTk3YWE3ZmM2Y2Q2OGUyNTA2MjRmOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HZtG_U39JrYOZXQTxj4DsRvQNRKOkVaSLudt3z4b-GU"> 不过开了S3睡眠，电量会一直显示100%
> 
> 会反复using AC 到darkwake，且不显示原因 <img alt="image" width="527" src="https://private-user-images.githubusercontent.com/43941885/361623546-2a6c077f-3bba-4039-83e9-18e672fe09e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MzIwMDMsIm5iZiI6MTcyNDczMTcwMywicGF0aCI6Ii80Mzk0MTg4NS8zNjE2MjM1NDYtMmE2YzA3N2YtM2JiYS00MDM5LTgzZTktMThlNjcyZmUwOWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA0MDgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjYWQzMjIxN2JlMTNiOWY4ZDAzNGE5Yzg2MTgzZGM1OTZjYjFhODZiYTU3YTJiNGRjNGZhNmY0NGM3NjI5MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BEv_NoEqYePcPw-6MXeZeIgvx5ByOsjca23ptxTuhBE">

下面那个c口会导致睡眠秒醒

**Comment by akwangl** [comment]
你这图片根本打不开

**Comment by JokerAB** [comment]
> 你这图片根本打不开

我也不知道咋上传了
<img width="699" alt="截图" src="https://github.com/user-attachments/assets/d3f02709-fa35-441d-8fef-48c7f1c31f9e">

**Comment by deanls1** [comment]
> > > Find A01D9343 4E534200 A0159344 41533301 Replace A3A3A3A3 A3A3A3A3 A3A3A3A3 A3A3A3A3就可以开启S3睡眠了 <img alt="截图" width="699" src="https://private-user-images.githubusercontent.com/49889696/361369150-c65eb917-87ff-435b-b28d-a286cd7f6d21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MjMyNDksIm5iZiI6MTcyNDcyMjk0OSwicGF0aCI6Ii80OTg4OTY5Ni8zNjEzNjkxNTAtYzY1ZWI5MTctODdmZi00MzViLWIyOGQtYTI4NmNkN2Y2ZDIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAxNDIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYTQwNmE5Mjk3M2U0ZGU3MzExNDIxODhjMjNlOTg3OTA2MmQ2MGFlYTk3YWE3ZmM2Y2Q2OGUyNTA2MjRmOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HZtG_U39JrYOZXQTxj4DsRvQNRKOkVaSLudt3z4b-GU"> 不过开了S3睡眠，电量会一直显示100%
> > 
> > 
> > 会反复using AC 到darkwake，且不显示原因 <img alt="image" width="527" src="https://private-user-images.githubusercontent.com/43941885/361623546-2a6c077f-3bba-4039-83e9-18e672fe09e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MzIwMDMsIm5iZiI6MTcyNDczMTcwMywicGF0aCI6Ii80Mzk0MTg4NS8zNjE2MjM1NDYtMmE2YzA3N2YtM2JiYS00MDM5LTgzZTktMThlNjcyZmUwOWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA0MDgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjYWQzMjIxN2JlMTNiOWY4ZDAzNGE5Yzg2MTgzZGM1OTZjYjFhODZiYTU3YTJiNGRjNGZhNmY0NGM3NjI5MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BEv_NoEqYePcPw-6MXeZeIgvx5ByOsjca23ptxTuhBE">
> 
> 下面那个c口会导致睡眠秒醒

左边除了充电另外的C口吗？

**Comment by JokerAB** [comment]
> > > > Find A01D9343 4E534200 A0159344 41533301 Replace A3A3A3A3 A3A3A3A3 A3A3A3A3 A3A3A3A3就可以开启S3睡眠了 <img alt="截图" width="699" src="https://private-user-images.githubusercontent.com/49889696/361369150-c65eb917-87ff-435b-b28d-a286cd7f6d21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MjMyNDksIm5iZiI6MTcyNDcyMjk0OSwicGF0aCI6Ii80OTg4OTY5Ni8zNjEzNjkxNTAtYzY1ZWI5MTctODdmZi00MzViLWIyOGQtYTI4NmNkN2Y2ZDIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAxNDIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYTQwNmE5Mjk3M2U0ZGU3MzExNDIxODhjMjNlOTg3OTA2MmQ2MGFlYTk3YWE3ZmM2Y2Q2OGUyNTA2MjRmOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HZtG_U39JrYOZXQTxj4DsRvQNRKOkVaSLudt3z4b-GU"> 不过开了S3睡眠，电量会一直显示100%
> > > 
> > > 
> > > 会反复using AC 到darkwake，且不显示原因 <img alt="image" width="527" src="https://private-user-images.githubusercontent.com/43941885/361623546-2a6c077f-3bba-4039-83e9-18e672fe09e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MzIwMDMsIm5iZiI6MTcyNDczMTcwMywicGF0aCI6Ii80Mzk0MTg4NS8zNjE2MjM1NDYtMmE2YzA3N2YtM2JiYS00MDM5LTgzZTktMThlNjcyZmUwOWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA0MDgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjYWQzMjIxN2JlMTNiOWY4ZDAzNGE5Yzg2MTgzZGM1OTZjYjFhODZiYTU3YTJiNGRjNGZhNmY0NGM3NjI5MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BEv_NoEqYePcPw-6MXeZeIgvx5ByOsjca23ptxTuhBE">
> > 
> > 
> > 下面那个c口会导致睡眠秒醒
> 
> 左边除了充电另外的C口吗？

对，这个插了设备就会秒醒，其他的不会

**Comment by deanls1** [comment]
> > > > > Find A01D9343 4E534200 A0159344 41533301 Replace A3A3A3A3 A3A3A3A3 A3A3A3A3 A3A3A3A3就可以开启S3睡眠了 <img alt="截图" width="699" src="https://private-user-images.githubusercontent.com/49889696/361369150-c65eb917-87ff-435b-b28d-a286cd7f6d21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MjMyNDksIm5iZiI6MTcyNDcyMjk0OSwicGF0aCI6Ii80OTg4OTY5Ni8zNjEzNjkxNTAtYzY1ZWI5MTctODdmZi00MzViLWIyOGQtYTI4NmNkN2Y2ZDIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAxNDIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYTQwNmE5Mjk3M2U0ZGU3MzExNDIxODhjMjNlOTg3OTA2MmQ2MGFlYTk3YWE3ZmM2Y2Q2OGUyNTA2MjRmOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HZtG_U39JrYOZXQTxj4DsRvQNRKOkVaSLudt3z4b-GU"> 不过开了S3睡眠，电量会一直显示100%
> > > > 
> > > > 
> > > > 会反复using AC 到darkwake，且不显示原因 <img alt="image" width="527" src="https://private-user-images.githubusercontent.com/43941885/361623546-2a6c077f-3bba-4039-83e9-18e672fe09e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MzIwMDMsIm5iZiI6MTcyNDczMTcwMywicGF0aCI6Ii80Mzk0MTg4NS8zNjE2MjM1NDYtMmE2YzA3N2YtM2JiYS00MDM5LTgzZTktMThlNjcyZmUwOWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA0MDgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjYWQzMjIxN2JlMTNiOWY4ZDAzNGE5Yzg2MTgzZGM1OTZjYjFhODZiYTU3YTJiNGRjNGZhNmY0NGM3NjI5MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BEv_NoEqYePcPw-6MXeZeIgvx5ByOsjca23ptxTuhBE">
> > > 
> > > 
> > > 下面那个c口会导致睡眠秒醒
> > 
> > 
> > 左边除了充电另外的C口吗？
> 
> 对，这个插了设备就会秒醒，其他的不会
不插设备依旧是会秒醒，也定制usb了，尝试过prw到xprw，都还是同样的问题，可以分享一下efi 吗？

**Comment by deanls1** [comment]
不插设备依旧是会秒醒，也定制usb了，尝试过prw到xprw，都还是同样的问题，可以分享一下efi吗？  @JokerAB

**Comment by lwh110221** [comment]
> 不插设备依旧是会秒醒，也定制usb了，尝试过prw到xprw，都还是同样的问题，可以分享一下efi吗？ @JokerAB

别折腾了 apu这玩意能睡就 不错了。别想着s3休眠了 极其不完美

**Comment by akwangl** [comment]
这本子奇葩的很，关闭一个xhc1.换白卡BCM94360CS2能进系统，但是只有蓝牙能用。。。。。。。还是老实用intel

**Comment by akwangl** [comment]
BIOS开启S3睡眠是能睡眠的。我没有用任何补丁，把原生电池修复应该就能完美支持s3睡眠

**Comment by lwh110221** [comment]
> BIOS开启S3睡眠是能睡眠的。我没有用任何补丁，把原生电池修复应该就能完美支持s3睡眠

咋弄

**Comment by ayakasuki** [comment]
> > > _No description provided._
> > 
> > 
> > 求问，打什么补丁
> 
> 打我的补丁

求补丁，补丁是合盖就能休眠吗

**Comment by lwh110221** [comment]
> > > > _No description provided._
> > > 
> > > 
> > > 求问，打什么补丁
> > 
> > 
> > 打我的补丁
> 
> 求补丁，补丁是合盖就能休眠吗

不是。休眠和睡眠不是一种概念。可以去搜搜
