### ISSUE TITLE
上周，Nootedred进行了更新，据说是修复了chrom硬件加速的问题

### ISSUE THREAD

**Issue by Wangxxis** [akwangl/RedmiBook-Pro-15S-hackintosh#2]
有效果吗？我打开时还是和之前一样出现了伪影之类的问题

**Comment by ayakasuki** [comment]
所以最后这个efi没修复对吗

**Comment by ayakasuki** [comment]
https://github.com/ChefKissInc/NootedRed/issues/158 这个才是这个月才开始解决硬解的问题 有了解决方案 看大佬push吧

**Comment by akwangl** [comment]
用opengl吧

**Comment by Wangxxis** [comment]
是的，等大佬push

**Comment by Wangxxis** [comment]
光标 箭头移至超链接时，变成小手时的闪烁问题有什么好的解决方法吗？https://forums.macrumors.com/threads/weird-cursor-behavior.2230749/  目前解决方法是#4楼 连接里面的内容：修改cursors里面pontinghand的大小

**Comment by Wangxxis** [comment]
使用idea系列的工具、wps、office时，这似乎没啥效果，一样闪的眼花缭乱
