### ISSUE TITLE
无线功能正常吗？大老

### ISSUE THREAD

**Issue by Joker-lm** [akwangl/RedmiBook-Pro-15S-hackintosh#3]
用次引导装到了无线不能连接，尝试连接立马就重启了，尝试登录ID，重启无法进入系统，怎么解决，大佬

**Comment by akwangl** [comment]
同样的机型么

**Comment by Joker-lm** [comment]
> 同样的机型么

嗯，同机型，同配置

**Comment by Joker-lm** [comment]
最后没办法，咸鱼上找了个人花钱装了，不过系统是 12.5.1，好像是

**Comment by JokerAB** [comment]
自带的网卡一切正常啊

**Comment by Joker-lm** [comment]
> 自带的网卡一切正常啊

可能是我不会装，纯小白

**Comment by ayakasuki** [comment]
> 用次引导装到了无线不能连接，尝试连接立马就重启了，尝试登录ID，重启无法进入系统，怎么解决，大佬

是airportitlwm的版本问题 2.2.0的不兼容 或者没下对对应venture的版本  去相关github下载最新的2.3.0的venture版本的就不会重启了。因为我当时也是这样 反馈群里了。但是efi没相应改

**Comment by ayakasuki** [comment]
> airportitlwm

https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.3.0 改完以后config.plist也把对应的airportitlwm的2.2.0改成2.3.0完事
